apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-primary
  namespace: expense-tracker
spec:
  serviceName: postgres-primary
  replicas: 1
  selector:
    matchLabels:
      app: postgres-primary
  template:
    metadata:
      labels:
        app: postgres-primary
    spec:
      containers:
        - name: postgres-primary
          image: bitnami/postgresql:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: master
            - name: POSTGRESQL_REPLICATION_USER
              value: repl_user
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: repl_password
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /bitnami/postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi