apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: expense-tracker
spec:
  type: ClusterIP
  selector:
    app: postgres-replica
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432