apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-tracker-config
  namespace: expense-tracker
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/expense_tracker"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"